"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-15

Hand-written rather than autogenerated so the same migration is portable
between Postgres (prod) and SQLite (tests without Docker). Uses
`sa.JSON` (not Postgres-specific JSONB) and `sa.Uuid` (cross-dialect).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text(), nullable=True),
        sa.Column("repo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "cells",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("visual", sa.JSON(), nullable=True),
        sa.Column("video", sa.JSON(), nullable=True),
        sa.Column("deep", sa.JSON(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("body", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "position", name="uq_cells_project_position"),
        sa.CheckConstraint("kind IN ('agent','markdown','empty')", name="ck_cells_kind"),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('in_progress','open','verified','rejected')",
            name="ck_cells_status",
        ),
    )
    op.create_index("ix_cells_project_id", "cells", ["project_id"])

    op.create_table(
        "verdicts",
        sa.Column("cell_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("by", sa.Text(), nullable=False, server_default=sa.text("'you'")),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cell_id"], ["cells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cell_id"),
        sa.CheckConstraint("state IN ('accept','reject')", name="ck_verdicts_state"),
    )

    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("cell_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_project_at", "events", ["project_id", "at"])


def downgrade() -> None:
    op.drop_index("ix_events_project_at", table_name="events")
    op.drop_table("events")
    op.drop_table("verdicts")
    op.drop_index("ix_cells_project_id", table_name="cells")
    op.drop_table("cells")
    op.drop_table("projects")
